<a href="https://colab.research.google.com/github/ahmad1bakundi-ops/data-engineering-journey/blob/main/lesson_06_sql_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install duckdb -q

In [2]:
import duckdb
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
DATA_PATH = '/content/drive/MyDrive/data-engineering-journey/lesson-02-data/'

# Create a DuckDB connection
con = duckdb.connect()

# Run our first SQL query!
result = con.execute(f"""
    SELECT *
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    LIMIT 5
""").fetchdf()

result

,order_id,customer_id,customer_name,customer_state,product,category,quantity,unit_price_ngn,order_date,payment_method,status
0,ORD-00651,1010,Folake Chukwu,Benin City,Bottle Garri 5kg,Groceries,3.0,4110.75,2024-09-09,Card,Shipped
1,ORD-00050,1177,Wale Akande,Abuja,Vegetable Oil 5 Litres,Groceries,1.0,13562.20,2024-09-07,None,Delivered
2,ORD-00102,1014,Grace Ojo,Ibadan,Tecno Spark 10 Phone,Electronics,1.0,140450.29,2024-12-02,None,Pending
3,ORD-00216,1300,Kemi Olawale,Enugu,Bottle Garri 5kg,Groceries,4.0,4312.23,2024-12-10,Bank Transfer,Cancelled
4,ORD-00566,1221,Gbenga Obi,Kaduna,JAMB Past Questions 2024,Books,1.0,3672.37,2024-04-02,Bank Transfer,Pending

In [4]:
con.execute(f"""
    SELECT order_id, product, unit_price_ngn
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    LIMIT 10
""").fetchdf()

    order_id                   product  unit_price_ngn
0  ORD-00651          Bottle Garri 5kg         4110.75
1  ORD-00050    Vegetable Oil 5 Litres        13562.20
2  ORD-00102      Tecno Spark 10 Phone       140450.29
3  ORD-00216          Bottle Garri 5kg         4312.23
4  ORD-00566  JAMB Past Questions 2024         3672.37
5  ORD-00169         Bluetooth Speaker        21356.79
6  ORD-00698            Leather Wallet         8488.98
7  ORD-00277  JAMB Past Questions 2024         3560.15
8  ORD-00164          Sunglasses UV400         9918.05
9  ORD-00260      Handbag Tote Leather        25346.81

In [5]:
con.execute(f"""
    SELECT *
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    WHERE status = 'Delivered'
    LIMIT 10
""").fetchdf()

,order_id,customer_id,customer_name,customer_state,product,category,quantity,unit_price_ngn,order_date,payment_method,status
0,ORD-00050,1177,Wale Akande,Abuja,Vegetable Oil 5 Litres,Groceries,1.0,13562.20,2024-09-07,None,Delivered
1,ORD-00698,1227,chinedu ogundimu,Owerri,Leather Wallet,Fashion,4.0,8488.98,2024-05-02,Bank Transfer,Delivered
2,ORD-00366,1266,Segun Hassan,Lagos,English Dictionary Oxford,Books,1.0,9274.11,2024-12-02,Wallet,Delivered
3,ORD-00089,1189,Gbenga Adesanya,Onitsha,Ankara Two-Piece,Fashion,4.0,22773.08,2024-09-07,Card,Delivered
4,ORD-00120,1259,Wale Adesanya,Lagos,Adire Print Dress,Fashion,1.0,14065.77,2024-04-02,Cash On Delivery,Delivered
5,ORD-00713,1069,Kunle Okonkwo,Port Harcourt,JAMB Past Questions 2024,Books,2.0,3495.29,2024-07-26,Cash On Delivery,Delivered
6,ORD-00485,1136,Yemi Ojo,Kaduna,Handbag Tote Leather,Fashion,2.0,24636.82,2024-04-09,Cash On Delivery,Delivered
7,ORD-00585,1209,Zara Adeyemi,Ibadan,Floor Standing Fan,Home Appliances,4.0,41918.22,2024-12-16,Bank Transfer,Delivered
8,ORD-00718,1218,Olumide Hassan,Onitsha,Baby Formula Tin 400g,Baby Care,1.0,8886.00,2024-02-15,None,Delivered
9,ORD-00081,1196,Kunle Eze,Aba,Peak Powdered Milk 900g,Groceries,10.0,6424.47,2024-12-03,Card,Delivered

In [6]:
con.execute(f"""
    SELECT order_id, product, unit_price_ngn, status
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    WHERE status = 'Delivered'
      AND unit_price_ngn > 50000
    LIMIT 10
""").fetchdf()

    order_id               product  unit_price_ngn     status
0  ORD-00613   Office Chair Swivel        79106.37  Delivered
1  ORD-00285     HP Laptop 15 Inch       484482.40  Delivered
2  ORD-00147   Office Chair Swivel        76168.79  Delivered
3  ORD-00547  Tecno Spark 10 Phone       151243.05  Delivered
4  ORD-00331      Generator 2.5KVA       177961.29  Delivered
5  ORD-00628     HP Laptop 15 Inch       464115.95  Delivered
6  ORD-00644    Samsung Galaxy A15       287965.36  Delivered
7  ORD-00210  Infinix Hot 30 Phone       163087.02  Delivered
8  ORD-00324   Office Chair Swivel        83163.80  Delivered
9  ORD-00425  Tecno Spark 10 Phone       150198.03  Delivered

In [7]:
con.execute(f"""
    SELECT
        customer_state,
        SUM(quantity * unit_price_ngn) AS total_revenue
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    GROUP BY customer_state
    ORDER BY total_revenue DESC
""").fetchdf()

   customer_state  total_revenue
0             Aba    10002262.75
1           Enugu     7146522.20
2          Kaduna     6532752.69
3         Onitsha     6415681.98
4   Port Harcourt     6003992.58
5             Jos     4771519.36
6      Benin City     4539118.50
7          Ibadan     4071759.95
8           Abuja     3561500.61
9          Owerri     3524683.87
10          Warri     3047521.61
11          Lagos     2794980.35
12           Kano     2711230.91
13           None     2461074.87
14        Calabar     2454855.13
15         Ilorin     2346786.73

In [12]:
con.execute(f"""
    SELECT
        category,
        AVG(quantity * unit_price_ngn) AS avg_revenue
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    GROUP BY category
    ORDER BY avg_revenue DESC
""").fetchdf()

          category    avg_revenue
0      Electronics  275342.627267
1        Furniture  175412.102381
2  Home Appliances  111128.676495
3          Fashion   42502.683191
4             None   28120.651429
5        Baby Care   16932.749722
6        Groceries   12257.653796
7            Books   12255.399104

In [13]:
con.execute(f"""
    SELECT *
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv' AS s
    LEFT JOIN '{DATA_PATH}nigerian_ecommerce_customers.csv' AS c
        ON s.customer_id = c.customer_id
    LIMIT 5
""").fetchdf()

,order_id,customer_id,customer_name,customer_state,product,category,quantity,unit_price_ngn,order_date,payment_method,status,customer_id_1,customer_name_1,email,phone,signup_date,tier,age,gender
0,ORD-00651,1010,Folake Chukwu,Benin City,Bottle Garri 5kg,Groceries,3.0,4110.75,2024-09-09,Card,Shipped,1010,Adebayo Abdullahi,adebayo.abdullahi@example.com,07058546900,2022-03-16,Bronze,51,Female
1,ORD-00050,1177,Wale Akande,Abuja,Vegetable Oil 5 Litres,Groceries,1.0,13562.20,2024-09-07,None,Delivered,1177,Bukky Aliyu,bukky.aliyu@example.com,09039917697,2022-05-20,Bronze,42,Male
2,ORD-00102,1014,Grace Ojo,Ibadan,Tecno Spark 10 Phone,Electronics,1.0,140450.29,2024-12-02,None,Pending,1014,Toyin Hassan,toyin.hassan@example.com,08168804191,2022-03-24,Silver,47,Female
3,ORD-00216,1300,Kemi Olawale,Enugu,Bottle Garri 5kg,Groceries,4.0,4312.23,2024-12-10,Bank Transfer,Cancelled,1300,Grace Bello,grace.bello@example.com,07015465978,2024-04-24,Silver,30,Female
4,ORD-00566,1221,Gbenga Obi,Kaduna,JAMB Past Questions 2024,Books,1.0,3672.37,2024-04-02,Bank Transfer,Pending,1221,Tobi Sani,tobi.sani@example.com,08056993952,2022-01-06,Bronze,25,Female

In [14]:
con.execute(f"""
    SELECT
        c.tier,
        COUNT(*) AS order_count,
        SUM(s.quantity * s.unit_price_ngn) AS total_revenue,
        AVG(s.quantity * s.unit_price_ngn) AS avg_order_value
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv' AS s
    LEFT JOIN '{DATA_PATH}nigerian_ecommerce_customers.csv' AS c
        ON s.customer_id = c.customer_id
    GROUP BY c.tier
    ORDER BY avg_order_value DESC
""").fetchdf()

       tier  order_count  total_revenue  avg_order_value
0      None           37     6323667.77    170909.939730
1    Bronze          402    42028905.41    104549.515945
2    Silver          173    16233397.92     93834.670058
3      Gold           83     6508433.87     78414.865904
4  Platinum           33     1624892.97     49239.180909

In [16]:
con.execute(f"""
    WITH delivered AS (
        SELECT *
        FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
        WHERE status = 'Delivered'
    )
    SELECT
        c.tier,
        AVG(d.quantity * d.unit_price_ngn) AS avg_revenue
    FROM delivered AS d
    LEFT JOIN '{DATA_PATH}nigerian_ecommerce_customers.csv' AS c
        ON d.customer_id = c.customer_id
    GROUP BY c.tier
    ORDER BY avg_revenue DESC
""").fetchdf()

       tier    avg_revenue
0      Gold  134844.003333
1    Silver  117894.414333
2      None   75989.585000
3    Bronze   61324.290889
4  Platinum   17008.040000

In [17]:
con.execute(f"""
    SELECT
        order_id,
        customer_id,
        order_date,
        quantity * unit_price_ngn AS revenue,
        SUM(quantity * unit_price_ngn) OVER (
            PARTITION BY customer_id
            ORDER BY order_date
        ) AS running_total
    FROM '{DATA_PATH}nigerian_ecommerce_sales_CLEAN.csv'
    ORDER BY customer_id, order_date
    LIMIT 20
""").fetchdf()

     order_id  customer_id order_date    revenue  running_total
0   ORD-00469         1000 2024-06-11   43621.08       43621.08
1   ORD-00174         1001 2024-02-05   36397.66       36397.66
2   ORD-00318         1001 2024-03-25    4048.05       40445.71
3   ORD-00019         1001 2024-10-11  135845.54      176291.25
4   ORD-00126         1002 2024-05-01    4413.79        4413.79
5   ORD-00365         1002 2024-11-07   37931.93       42345.72
6   ORD-00290         1003 2024-02-02    6266.35        6266.35
7   ORD-00189         1003 2024-07-10   22346.40       28612.75
8   ORD-00241         1005 2024-05-17    7538.71        7538.71
9   ORD-00668         1005 2024-07-03   43097.85       50636.56
10  ORD-00349         1005 2024-10-16    3397.45       54034.01
11  ORD-00169         1005 2024-12-17   21356.79       75390.80
12  ORD-00484         1006 2024-08-09   14460.12       14460.12
13  ORD-00167         1007 2024-02-14   12814.02       12814.02
14  ORD-00178         1008 2024-08-12  458760.37      458760.37
15  ORD-00195         1008 2024-10-15   16613.64      475374.01
16  ORD-00497         1008 2024-12-07    4430.68      479804.69
17  ORD-00356         1009 2024-07-29   83120.85       83120.85
18  ORD-00614         1009 2024-08-08    3353.97       86474.82
19  ORD-00571         1010 2024-07-22   26628.58       26628.58